spring:
  application:
    name: my-blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: caffeine
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 25MB
  security:
    jwt:
      secret: ${JWT_SECRET:my-secret-key}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600}  # 1 hour
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:172800}  # 2 days
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
    url: ${AWS_S3_ENDPOINT_URL}
    dev-url: ${CLOUDFLARE_BUCKET_SUBDOMAIN}
server:
  port: 9997