spring:
  application:
    name: my-blog
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${DB_TYPE:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:my_blog}?serverTimezone=KST
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  cache:
    type: caffeine
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
    url: ${AWS_S3_ENDPOINT_URL}
    dev-url: ${CLOUDFLARE_BUCKET_SUBDOMAIN}
server:
  port: 9997